wandb_version: 1

lr:
  desc: null
  value: 1.0479817717074484e-05
weight_decay:
  desc: null
  value: 1.4022093547948133e-05
hidden_size:
  desc: null
  value: 100
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 211
num_layers:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700238288.292365
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
