wandb_version: 1

lr:
  desc: null
  value: 0.001615808769535866
weight_decay:
  desc: null
  value: 3.944342048731515e-05
hidden_size:
  desc: null
  value: 123
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 184
num_layers:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700238206.22152
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
