wandb_version: 1

lr:
  desc: null
  value: 0.004577066286965899
weight_decay:
  desc: null
  value: 0.0001228439172949857
hidden_size:
  desc: null
  value: 103
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 298
num_layers:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700238336.229968
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
