wandb_version: 1

lr:
  desc: null
  value: 0.00024145035285286874
weight_decay:
  desc: null
  value: 9.941609318037565e-05
hidden_size:
  desc: null
  value: 96
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 166
num_layers:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700232271.858259
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
