wandb_version: 1

lr:
  desc: null
  value: 1.8373854241744095e-05
weight_decay:
  desc: null
  value: 0.0001689916609759784
hidden_size:
  desc: null
  value: 103
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 212
num_layers:
  desc: null
  value: 212
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700249390.961542
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
