wandb_version: 1

lr:
  desc: null
  value: 0.0007921675949914857
weight_decay:
  desc: null
  value: 1.741250358277237e-05
hidden_size:
  desc: null
  value: 124
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 300
num_layers:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700250754.243737
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
