wandb_version: 1

lr:
  desc: null
  value: 0.0030133056083382513
weight_decay:
  desc: null
  value: 2.366877322726593e-05
hidden_size:
  desc: null
  value: 92
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 289
num_layers:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700232432.566173
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
