wandb_version: 1

lr:
  desc: null
  value: 0.017842448683891454
weight_decay:
  desc: null
  value: 0.0002565204727817651
hidden_size:
  desc: null
  value: 102
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 256
num_layers:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700231221.193134
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
