wandb_version: 1

lr:
  desc: null
  value: 0.002337774709361411
weight_decay:
  desc: null
  value: 0.00034829421733783086
hidden_size:
  desc: null
  value: 36
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 276
num_layers:
  desc: null
  value: 276
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700247704.540144
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
