wandb_version: 1

lr:
  desc: null
  value: 6.490834342745903e-05
weight_decay:
  desc: null
  value: 0.0006334684867977072
hidden_size:
  desc: null
  value: 115
attn_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 262
num_layers:
  desc: null
  value: 262
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700247535.96867
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
